/*Author: Daniel Elias Becerra A01208905
Description: This class creates the GUI where the user can cboose which game file to open and continue playing or view results.
Date: 20/04/18
*/

package tictactoe;

import logic.*;//Imports the classes in the package logic: Game and Player

public class Choose_File extends javax.swing.JFrame {

    public Choose_File() {// Constructor
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chooser = new javax.swing.JFileChooser();
        dots_gif = new javax.swing.JLabel();
        menu_button = new javax.swing.JButton();
        tresd = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooserActionPerformed(evt);
            }
        });
        getContentPane().add(chooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, 310));

        dots_gif.setFont(new java.awt.Font("Pokemon Hollow", 1, 60)); // NOI18N
        dots_gif.setForeground(new java.awt.Color(255, 255, 255));
        dots_gif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/images_tictactoe/dots.gif"))); // NOI18N
        getContentPane().add(dots_gif, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 320, 260));

        menu_button.setBackground(new java.awt.Color(10, 22, 38));
        menu_button.setFont(new java.awt.Font("TESLA", 1, 18)); // NOI18N
        menu_button.setForeground(new java.awt.Color(255, 255, 255));
        menu_button.setText("BACK TO  MENU");
        menu_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_button.setIconTextGap(0);
        menu_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_buttonMouseClicked(evt);
            }
        });
        getContentPane().add(menu_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 230, 50));

        tresd.setFont(new java.awt.Font("Pokemon Hollow", 1, 60)); // NOI18N
        tresd.setForeground(new java.awt.Color(255, 255, 255));
        tresd.setText("3D");
        getContentPane().add(tresd, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 110, 110));

        title.setFont(new java.awt.Font("TESLA", 1, 60)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("TIC TAC TOE");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 570, 110));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/images_tictactoe/TicTacToeMainBackground.png"))); // NOI18N
        background.setText("jLabel1");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_buttonMouseClicked
       new Menu().setVisible(true); // puts the menu frame.
        setVisible(false);
    }//GEN-LAST:event_menu_buttonMouseClicked

    private void chooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooserActionPerformed
        
        if (chooser.APPROVE_OPTION==0) { // If user chooses to button "Abrir" or "OPEN"
            String filename=chooser.getSelectedFile().getName(); // get the filename to be opened
            new Play_Frame(filename).setVisible(true); // calls a different constructor that will deserialized the previous game with the filename that was chosen.
            setVisible(false); 
        }
    }//GEN-LAST:event_chooserActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JFileChooser chooser;
    private javax.swing.JLabel dots_gif;
    private javax.swing.JButton menu_button;
    private javax.swing.JLabel title;
    private javax.swing.JLabel tresd;
    // End of variables declaration//GEN-END:variables
}
