/*Author: Daniel Elias Becerra A01208905
Description: This class creates the GUI for the main menu with the buttons play, open and rules.
Date: 17/04/18
*/

package tictactoe;

import logic.*;//Imports the classes in the package logic: Game and Player

public class Menu extends javax.swing.JFrame {

    public Menu() {// Creates new form Menu
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        score_button = new javax.swing.JButton();
        rules_button = new javax.swing.JButton();
        play_button = new javax.swing.JButton();
        dots_gif = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        tresd = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        score_button.setBackground(new java.awt.Color(10, 22, 38));
        score_button.setFont(new java.awt.Font("TESLA", 1, 28)); // NOI18N
        score_button.setForeground(new java.awt.Color(255, 255, 255));
        score_button.setText("OPEN");
        score_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        score_button.setIconTextGap(0);
        score_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                score_buttonMouseClicked(evt);
            }
        });
        getContentPane().add(score_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 400, 160, 50));

        rules_button.setBackground(new java.awt.Color(10, 22, 38));
        rules_button.setFont(new java.awt.Font("TESLA", 1, 28)); // NOI18N
        rules_button.setForeground(new java.awt.Color(255, 255, 255));
        rules_button.setText("RULES");
        rules_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rules_button.setIconTextGap(0);
        rules_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rules_buttonMouseClicked(evt);
            }
        });
        getContentPane().add(rules_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 180, 50));

        play_button.setBackground(new java.awt.Color(10, 22, 38));
        play_button.setFont(new java.awt.Font("TESLA", 1, 28)); // NOI18N
        play_button.setForeground(new java.awt.Color(255, 255, 255));
        play_button.setText("PLAY");
        play_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        play_button.setIconTextGap(0);
        play_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                play_buttonMouseClicked(evt);
            }
        });
        getContentPane().add(play_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 180, 50));

        dots_gif.setFont(new java.awt.Font("Pokemon Hollow", 1, 60)); // NOI18N
        dots_gif.setForeground(new java.awt.Color(255, 255, 255));
        dots_gif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/images_tictactoe/dots.gif"))); // NOI18N
        getContentPane().add(dots_gif, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 410, 280));

        title.setFont(new java.awt.Font("TESLA", 1, 60)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("TIC TAC TOE");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 570, 110));

        tresd.setFont(new java.awt.Font("Pokemon Hollow", 1, 60)); // NOI18N
        tresd.setForeground(new java.awt.Color(255, 255, 255));
        tresd.setText("3D");
        getContentPane().add(tresd, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 110, 110));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/images_tictactoe/TicTacToeMainBackground.png"))); // NOI18N
        background.setText("jLabel1");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void score_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_score_buttonMouseClicked

        new Choose_File().setVisible(true); // Opens the choose file frame.
        setVisible(false); 
    }//GEN-LAST:event_score_buttonMouseClicked

    private void rules_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rules_buttonMouseClicked
       new Rules().setVisible(true); // Opens the rules frame.
        setVisible(false);
    }//GEN-LAST:event_rules_buttonMouseClicked

    private void play_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_play_buttonMouseClicked
        Players players = new Players(); // Opens the frame to inctroduce Player names.
        players.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_play_buttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) { // MAIN METHOD
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel dots_gif;
    private javax.swing.JButton play_button;
    private javax.swing.JButton rules_button;
    private javax.swing.JButton score_button;
    private javax.swing.JLabel title;
    private javax.swing.JLabel tresd;
    // End of variables declaration//GEN-END:variables
}
