/*Author: Daniel Elias Becerra A01208905
Description: This class creates the main GUI where the players play the TicTacToe Game
Date: 17/04/18 - 22/04/18
*/ 

package tictactoe;

import logic.*;//Imports the classes in the package logic: Game and Player

public class Play_Frame extends javax.swing.JFrame {
    private int turn=0; // TURN
    private Game game; // GAME - THE CLASS WITH THE LOGIC
    private Player player1; // THIS CLASS CREATES THE OBJECTS OF PLAYER - COMPOSITION
    private Player player2;
    private int[][][] grid=new int[3][3][3]; // THE 3D GRID TO BE USED IN THE LOGIC IS SENT TO THE GAME CLASS.
    private String result=""; // RESULT OF WHO WINS.
    private String name1; // NAMES OF PLAYERS WHICH ARE ATTRIBUTES TO BE USED IN THE CLASS PLAYER TO CREATE OBJECTS.
    private String name2;
    private String filename; // FILENAME OF THE FILE TO BE OPENED IN CASE A DESERIALIZATION OR SERIALIZATION OCCURS.
    private ObjectWriter game_writer=new ObjectWriter(); // SERIALIZES THE GAME WHEN IS SAVED BY THE USER
    private javax.swing.JButton[][][] buttons=new javax.swing.JButton[3][3][3];// array of all buttons with a position equal to the 3d array in the logic
    
    
    public Play_Frame(String name1, String name2) {//Creates new form Play_Frame
        initComponents();
        setLocationRelativeTo(null);
        file_label.setVisible(false);
        done_button.setVisible(false);
        filename_field.setVisible(false);
        save_label.setVisible(false);
        turn_label2.setVisible(false);
        this.name1=name1;
        this.name2=name2;
        player1= new Player(name1, 1); // CLASS PLAY FRAME CREATES THE OBJECTS OF PLAYER. COMPOSITION
        player2= new Player(name2, 2);
        game= new Game(player1, player2,grid, turn); // CLASS PLAY FRAME CREATES OBJECT OF GAME - LOGIC BEHIND. COMPOSITION
        turn_label1.setText("player1 turn: "+name1);
        turn_label3.setText("player 1: "+name1);
        turn_label2.setVisible(true);
        turn_label2.setText("player 2: "+name2);
    }
    
    public Play_Frame(String filename) {//Creates new form Play_Frame // it is another onstrcutor that receives no parameters.
        //This constructor receives no parameters as the whole Game logic will be retrieved from the txt file with the save data.
        initComponents();
        setLocationRelativeTo(null);
        file_label.setVisible(false);
        done_button.setVisible(false);
        filename_field.setVisible(false);
        save_label.setVisible(false);
        turn_label2.setVisible(false);
        
        ObjectReader reader=new ObjectReader(); // CREATES OBJECT READER OBJECT TO DESERIALIZE A PREVIOUSLY SAVED GAME
        this.game=reader.read(filename);
        this.player1=game.getPlayer1(); // RETRIEVES THE PLAYER OBJECTS  STORED IN THE NOW DESERIALIZED GAME OBJECT
        this.player2=game.getPlayer2();
        this.name1=player1.getName(); // STORES THE NAMES TO BE DISPLAYED ON THE PAY FRAME GUI.
        this.name2=player2.getName();
        this.grid=game.getGrid(); // GETS HOW THE LOGICAL GRID WAS WHEN THE DESERIALIZED GAME WAS SAVED.
        this.buttons=buttons;
        saveButtons();
        initializeSavedGame();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        a1 = new javax.swing.JButton();
        a2 = new javax.swing.JButton();
        a3 = new javax.swing.JButton();
        a4 = new javax.swing.JButton();
        a5 = new javax.swing.JButton();
        a6 = new javax.swing.JButton();
        a7 = new javax.swing.JButton();
        a8 = new javax.swing.JButton();
        a9 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        c1 = new javax.swing.JButton();
        c2 = new javax.swing.JButton();
        c3 = new javax.swing.JButton();
        c4 = new javax.swing.JButton();
        c5 = new javax.swing.JButton();
        c6 = new javax.swing.JButton();
        c7 = new javax.swing.JButton();
        c8 = new javax.swing.JButton();
        c9 = new javax.swing.JButton();
        dots_gif = new javax.swing.JLabel();
        tresd = new javax.swing.JLabel();
        title1 = new javax.swing.JLabel();
        layerA_graphic = new javax.swing.JLabel();
        turn_label7 = new javax.swing.JLabel();
        layerB_graphic = new javax.swing.JLabel();
        layerC_graphic = new javax.swing.JLabel();
        results_label = new javax.swing.JLabel();
        turn_label1 = new javax.swing.JLabel();
        turn_label3 = new javax.swing.JLabel();
        turn_label5 = new javax.swing.JLabel();
        turn_label6 = new javax.swing.JLabel();
        turn_label4 = new javax.swing.JLabel();
        turn_label2 = new javax.swing.JLabel();
        done_button = new javax.swing.JButton();
        save_button = new javax.swing.JButton();
        menu_button1 = new javax.swing.JButton();
        save_label = new javax.swing.JLabel();
        file_label = new javax.swing.JLabel();
        filename_field = new javax.swing.JTextField();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        a1.setBackground(new java.awt.Color(10, 22, 38));
        a1.setFont(new java.awt.Font("TESLA", 1, 36)); // NOI18N
        a1.setForeground(new java.awt.Color(255, 255, 255));
        a1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        a1.setIconTextGap(0);
        a1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a1MouseClicked(evt);
            }
        });
        getContentPane().add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 70, 70));

        a2.setBackground(new java.awt.Color(10, 22, 38));
        a2.setFont(new java.awt.Font("TESLA", 1, 36)); // NOI18N
        a2.setForeground(new java.awt.Color(255, 255, 255));
        a2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        a2.setIconTextGap(0);
        a2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a2MouseClicked(evt);
            }
        });
        getContentPane().add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 70, 70));

        a3.setBackground(new java.awt.Color(10, 22, 38));
        a3.setFont(new java.awt.Font("TESLA", 1, 36)); // NOI18N
        a3.setForeground(new java.awt.Color(255, 255, 255));
        a3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        a3.setIconTextGap(0);
        a3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a3MouseClicked(evt);
            }
        });
        getContentPane().add(a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 70, 70));

        a4.setBackground(new java.awt.Color(10, 22, 38));
        a4.setFont(new java.awt.Font("TESLA", 1, 36)); // NOI18N
        a4.setForeground(new java.awt.Color(255, 255, 255));
        a4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        a4.setIconTextGap(0);
        a4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a4MouseClicked(evt);
            }
        });
        getContentPane().add(a4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 70, 70));

        a5.setBackground(new java.awt.Color(10, 22, 38));
        a5.setFont(new java.awt.Font("TESLA", 1, 36)); // NOI18N
        a5.setForeground(new java.awt.Color(255, 255, 255));
        a5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        a5.setIconTextGap(0);
        a5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a5MouseClicked(evt);
            }
        });
        getContentPane().add(a5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 70, 70));

        a6.setBackground(new java.awt.Color(10, 22, 38));
        a6.setFont(new java.awt.Font("TESLA", 1, 36)); // NOI18N
        a6.setForeground(new java.awt.Color(255, 255, 255));
        a6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        a6.setIconTextGap(0);
        a6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a6MouseClicked(evt);
            }
        });
        getContentPane().add(a6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 70, 70));

        a7.setBackground(new java.awt.Color(10, 22, 38));
        a7.setFont(new java.awt.Font("TESLA", 1, 36)); // NOI18N
        a7.setForeground(new java.awt.Color(255, 255, 255));
        a7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        a7.setIconTextGap(0);
        a7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a7MouseClicked(evt);
            }
        });
        getContentPane().add(a7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 70, 80));

        a8.setBackground(new java.awt.Color(10, 22, 38));
        a8.setFont(new java.awt.Font("TESLA", 1, 36)); // NOI18N
        a8.setForeground(new java.awt.Color(255, 255, 255));
        a8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        a8.setIconTextGap(0);
        a8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a8MouseClicked(evt);
            }
        });
        getContentPane().add(a8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 70, 80));

        a9.setBackground(new java.awt.Color(10, 22, 38));
        a9.setFont(new java.awt.Font("TESLA", 1, 36)); // NOI18N
        a9.setForeground(new java.awt.Color(255, 255, 255));
        a9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        a9.setIconTextGap(0);
        a9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a9MouseClicked(evt);
            }
        });
        getContentPane().add(a9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 70, 80));

        b1.setBackground(new java.awt.Color(10, 22, 38));
        b1.setFont(new java.awt.Font("TESLA", 1, 36)); // NOI18N
        b1.setForeground(new java.awt.Color(255, 255, 255));
        b1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b1.setIconTextGap(0);
        b1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b1MouseClicked(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 70, 70));

        b2.setBackground(new java.awt.Color(10, 22, 38));
        b2.setFont(new java.awt.Font("TESLA", 1, 36)); // NOI18N
        b2.setForeground(new java.awt.Color(255, 255, 255));
        b2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b2.setIconTextGap(0);
        b2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b2MouseClicked(evt);
            }
        });
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 70, 70));

        b3.setBackground(new java.awt.Color(10, 22, 38));
        b3.setFont(new java.awt.Font("TESLA", 1, 36)); // NOI18N
        b3.setForeground(new java.awt.Color(255, 255, 255));
        b3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b3.setIconTextGap(0);
        b3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b3MouseClicked(evt);
            }
        });
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 70, 70));

        b4.setBackground(new java.awt.Color(10, 22, 38));
        b4.setFont(new java.awt.Font("TESLA", 1, 36)); // NOI18N
        b4.setForeground(new java.awt.Color(255, 255, 255));
        b4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b4.setIconTextGap(0);
        b4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b4MouseClicked(evt);
            }
        });
        getContentPane().add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 70, 70));

        b5.setBackground(new java.awt.Color(10, 22, 38));
        b5.setFont(new java.awt.Font("TESLA", 1, 36)); // NOI18N
        b5.setForeground(new java.awt.Color(255, 255, 255));
        b5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b5.setIconTextGap(0);
        b5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b5MouseClicked(evt);
            }
        });
        getContentPane().add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 70, 70));

        b6.setBackground(new java.awt.Color(10, 22, 38));
        b6.setFont(new java.awt.Font("TESLA", 1, 36)); // NOI18N
        b6.setForeground(new java.awt.Color(255, 255, 255));
        b6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b6.setIconTextGap(0);
        b6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b6MouseClicked(evt);
            }
        });
        getContentPane().add(b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 70, 70));

        b7.setBackground(new java.awt.Color(10, 22, 38));
        b7.setFont(new java.awt.Font("TESLA", 1, 36)); // NOI18N
        b7.setForeground(new java.awt.Color(255, 255, 255));
        b7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b7.setIconTextGap(0);
        b7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b7MouseClicked(evt);
            }
        });
        getContentPane().add(b7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 70, 80));

        b8.setBackground(new java.awt.Color(10, 22, 38));
        b8.setFont(new java.awt.Font("TESLA", 1, 36)); // NOI18N
        b8.setForeground(new java.awt.Color(255, 255, 255));
        b8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b8.setIconTextGap(0);
        b8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b8MouseClicked(evt);
            }
        });
        getContentPane().add(b8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 70, 80));

        b9.setBackground(new java.awt.Color(10, 22, 38));
        b9.setFont(new java.awt.Font("TESLA", 1, 36)); // NOI18N
        b9.setForeground(new java.awt.Color(255, 255, 255));
        b9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b9.setIconTextGap(0);
        b9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b9MouseClicked(evt);
            }
        });
        getContentPane().add(b9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 70, 80));

        c1.setBackground(new java.awt.Color(10, 22, 38));
        c1.setFont(new java.awt.Font("TESLA", 1, 36)); // NOI18N
        c1.setForeground(new java.awt.Color(255, 255, 255));
        c1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c1.setIconTextGap(0);
        c1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c1MouseClicked(evt);
            }
        });
        getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 350, 70, 70));

        c2.setBackground(new java.awt.Color(10, 22, 38));
        c2.setFont(new java.awt.Font("TESLA", 1, 36)); // NOI18N
        c2.setForeground(new java.awt.Color(255, 255, 255));
        c2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c2.setIconTextGap(0);
        c2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c2MouseClicked(evt);
            }
        });
        getContentPane().add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 350, 70, 70));

        c3.setBackground(new java.awt.Color(10, 22, 38));
        c3.setFont(new java.awt.Font("TESLA", 1, 36)); // NOI18N
        c3.setForeground(new java.awt.Color(255, 255, 255));
        c3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c3.setIconTextGap(0);
        c3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c3MouseClicked(evt);
            }
        });
        getContentPane().add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 350, 70, 70));

        c4.setBackground(new java.awt.Color(10, 22, 38));
        c4.setFont(new java.awt.Font("TESLA", 1, 36)); // NOI18N
        c4.setForeground(new java.awt.Color(255, 255, 255));
        c4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c4.setIconTextGap(0);
        c4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c4MouseClicked(evt);
            }
        });
        getContentPane().add(c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 420, 70, 70));

        c5.setBackground(new java.awt.Color(10, 22, 38));
        c5.setFont(new java.awt.Font("TESLA", 1, 36)); // NOI18N
        c5.setForeground(new java.awt.Color(255, 255, 255));
        c5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c5.setIconTextGap(0);
        c5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c5MouseClicked(evt);
            }
        });
        getContentPane().add(c5, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 420, 70, 70));

        c6.setBackground(new java.awt.Color(10, 22, 38));
        c6.setFont(new java.awt.Font("TESLA", 1, 36)); // NOI18N
        c6.setForeground(new java.awt.Color(255, 255, 255));
        c6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c6.setIconTextGap(0);
        c6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c6MouseClicked(evt);
            }
        });
        getContentPane().add(c6, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 420, 70, 70));

        c7.setBackground(new java.awt.Color(10, 22, 38));
        c7.setFont(new java.awt.Font("TESLA", 1, 36)); // NOI18N
        c7.setForeground(new java.awt.Color(255, 255, 255));
        c7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c7.setIconTextGap(0);
        c7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c7MouseClicked(evt);
            }
        });
        getContentPane().add(c7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 490, 70, 80));

        c8.setBackground(new java.awt.Color(10, 22, 38));
        c8.setFont(new java.awt.Font("TESLA", 1, 36)); // NOI18N
        c8.setForeground(new java.awt.Color(255, 255, 255));
        c8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c8.setIconTextGap(0);
        c8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c8MouseClicked(evt);
            }
        });
        getContentPane().add(c8, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 490, 70, 80));

        c9.setBackground(new java.awt.Color(10, 22, 38));
        c9.setFont(new java.awt.Font("TESLA", 1, 36)); // NOI18N
        c9.setForeground(new java.awt.Color(255, 255, 255));
        c9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        c9.setIconTextGap(0);
        c9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c9MouseClicked(evt);
            }
        });
        getContentPane().add(c9, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 490, 70, 80));

        dots_gif.setFont(new java.awt.Font("Pokemon Hollow", 1, 60)); // NOI18N
        dots_gif.setForeground(new java.awt.Color(255, 255, 255));
        dots_gif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/images_tictactoe/dots.gif"))); // NOI18N
        getContentPane().add(dots_gif, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 300, 190));

        tresd.setFont(new java.awt.Font("Pokemon Hollow", 1, 40)); // NOI18N
        tresd.setForeground(new java.awt.Color(255, 255, 255));
        tresd.setText("3D");
        getContentPane().add(tresd, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 60, 50));

        title1.setFont(new java.awt.Font("TESLA", 1, 30)); // NOI18N
        title1.setForeground(new java.awt.Color(255, 255, 255));
        title1.setText("TIC TAC TOE");
        getContentPane().add(title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 260, 50));

        layerA_graphic.setFont(new java.awt.Font("TESLA", 1, 30)); // NOI18N
        layerA_graphic.setForeground(new java.awt.Color(255, 255, 255));
        layerA_graphic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/images_tictactoe/3d.png"))); // NOI18N
        layerA_graphic.setText("TIC TAC TOE");
        getContentPane().add(layerA_graphic, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 260, 260));

        turn_label7.setFont(new java.awt.Font("TESLA", 2, 30)); // NOI18N
        turn_label7.setForeground(new java.awt.Color(255, 52, 120));
        turn_label7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/images_tictactoe/cube.png"))); // NOI18N
        getContentPane().add(turn_label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, 170, 160));

        layerB_graphic.setFont(new java.awt.Font("TESLA", 1, 30)); // NOI18N
        layerB_graphic.setForeground(new java.awt.Color(255, 255, 255));
        layerB_graphic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/images_tictactoe/3d.png"))); // NOI18N
        layerB_graphic.setText("TIC TAC TOE");
        getContentPane().add(layerB_graphic, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 260, 260));

        layerC_graphic.setFont(new java.awt.Font("TESLA", 1, 30)); // NOI18N
        layerC_graphic.setForeground(new java.awt.Color(255, 255, 255));
        layerC_graphic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/images_tictactoe/3d.png"))); // NOI18N
        layerC_graphic.setText("TIC TAC TOE");
        getContentPane().add(layerC_graphic, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 320, 260, 260));

        results_label.setFont(new java.awt.Font("TESLA", 2, 35)); // NOI18N
        results_label.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(results_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 250, 380, 60));

        turn_label1.setFont(new java.awt.Font("TESLA", 2, 30)); // NOI18N
        turn_label1.setForeground(new java.awt.Color(255, 255, 255));
        turn_label1.setText("turn:");
        getContentPane().add(turn_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 470, 60));

        turn_label3.setFont(new java.awt.Font("TESLA", 2, 30)); // NOI18N
        turn_label3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(turn_label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 470, 60));

        turn_label5.setFont(new java.awt.Font("TESLA", 2, 30)); // NOI18N
        turn_label5.setForeground(new java.awt.Color(255, 247, 0));
        turn_label5.setText("layer 3");
        getContentPane().add(turn_label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 560, 140, 60));

        turn_label6.setFont(new java.awt.Font("TESLA", 2, 30)); // NOI18N
        turn_label6.setForeground(new java.awt.Color(255, 52, 120));
        turn_label6.setText("layer 2");
        getContentPane().add(turn_label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, 140, 60));

        turn_label4.setFont(new java.awt.Font("TESLA", 2, 30)); // NOI18N
        turn_label4.setForeground(new java.awt.Color(10, 220, 220));
        turn_label4.setText("layer |");
        getContentPane().add(turn_label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 140, 60));

        turn_label2.setFont(new java.awt.Font("TESLA", 2, 30)); // NOI18N
        turn_label2.setForeground(new java.awt.Color(255, 255, 255));
        turn_label2.setText("turn:");
        getContentPane().add(turn_label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 470, 60));

        done_button.setBackground(new java.awt.Color(10, 22, 38));
        done_button.setFont(new java.awt.Font("TESLA", 1, 24)); // NOI18N
        done_button.setForeground(new java.awt.Color(255, 255, 255));
        done_button.setText("DONE");
        done_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        done_button.setIconTextGap(0);
        done_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                done_buttonMouseClicked(evt);
            }
        });
        getContentPane().add(done_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 500, 140, 60));

        save_button.setBackground(new java.awt.Color(10, 22, 38));
        save_button.setFont(new java.awt.Font("TESLA", 1, 24)); // NOI18N
        save_button.setForeground(new java.awt.Color(255, 255, 255));
        save_button.setText("SAVE");
        save_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save_button.setIconTextGap(0);
        save_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                save_buttonMouseClicked(evt);
            }
        });
        getContentPane().add(save_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 140, 60));

        menu_button1.setBackground(new java.awt.Color(10, 22, 38));
        menu_button1.setFont(new java.awt.Font("TESLA", 1, 18)); // NOI18N
        menu_button1.setForeground(new java.awt.Color(255, 255, 255));
        menu_button1.setText("BACK TO  MENU");
        menu_button1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_button1.setIconTextGap(0);
        menu_button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_button1MouseClicked(evt);
            }
        });
        getContentPane().add(menu_button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 230, 50));

        save_label.setFont(new java.awt.Font("TESLA", 2, 24)); // NOI18N
        save_label.setForeground(new java.awt.Color(255, 255, 255));
        save_label.setText("Your game has been saved!");
        getContentPane().add(save_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 550, 40));

        file_label.setFont(new java.awt.Font("TESLA", 2, 24)); // NOI18N
        file_label.setForeground(new java.awt.Color(255, 255, 255));
        file_label.setText("insert save file name.txt:");
        getContentPane().add(file_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 550, 40));

        filename_field.setBackground(new java.awt.Color(8, 55, 77));
        filename_field.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        filename_field.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(filename_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 350, 50));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/images_tictactoe/TicTacToeMainBackground.png"))); // NOI18N
        background.setText("jLabel1");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
   public void initializeSavedGame(){ // Sets the names that were displayed when the GAME was saved.
        turn_label1.setText("player1 turn: "+name1);
        loadSavedBoard(game); // Load wehre the X's and O's where.
        game.checkWin(); // checks if someone had already won.
        result=game.checkWin(); // dispalys results and names of players that played the game.
        turn_label3.setText("player 1: "+name1);
        turn_label2.setVisible(true);
        turn_label2.setText("player 2: "+name2);
        results_label.setText(result);
}
    
   public void saveButtons(){ // saves all the buttons in the Array of buttons
        buttons[0][0][0]=a1; // can I do this here or do I need to send it to the logic? **********************
        buttons[0][0][1]=a2;
        buttons[0][0][2]=a3;
        buttons[0][1][0]=a4;
        buttons[0][1][1]=a5;
        buttons[0][1][2]=a6;
        buttons[0][2][0]=a7;
        buttons[0][2][1]=a8;
        buttons[0][2][2]=a9;
        
        buttons[1][0][0]=b1;
        buttons[1][0][1]=b2;
        buttons[1][0][2]=b3;
        buttons[1][1][0]=b4;
        buttons[1][1][1]=b5;
        buttons[1][1][2]=b6;
        buttons[1][2][0]=b7;
        buttons[1][2][1]=b8;
        buttons[1][2][2]=b9;
        
        buttons[2][0][0]=c1;
        buttons[2][0][1]=c2;
        buttons[2][0][2]=c3;
        buttons[2][1][0]=c4;
        buttons[2][1][1]=c5;
        buttons[2][1][2]=c6;
        buttons[2][2][0]=c7;
        buttons[2][2][1]=c8;
        buttons[2][2][2]=c9;
    }
    
   public void loadSavedBoard(Game game){ // Method to change the text in the button based on what the log 3d Array grid has in its values.
      // loads how the grid or tic tac toe board was when the user selected save.
    int i=0;
    int j=0;
    int k=0;
        for(i=0;i<3;i++){ //MOVING ON Z AXIS OR THE LAYERS
            for(j=0;j<3;j++){//MOVING ON THE Y AXIS OR THE ROWS
                for(k=0; k<3; k++){//MOVING ON THE X AXIS OR THE COLUMNS
                        if(grid[i][j][k]==2){ //Gives point to each player to sum and know if they have completed 3 in a row.
                                buttons[i][j][k].setText("O");
                            }
                           
                            if(grid[i][j][k]==1){
                                buttons[i][j][k].setText("X");
                            }
                }
            }
        }
   }
   
    private void a2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a2MouseClicked
       if(a2.getText()==""&&result==""){
        if(turn==1){ // ALL GRID BUTTONS HAVE THE SAME LINES OF CODE IN THEM
            turn_label1.setText("player1 turn: "+name1);
            a2.setText("X");
            turn=0;
            
            grid=game.getGrid();
            grid[0][0][1]=1; // The position of the grid changes, 1 is stored in  the logic grid to indicate a O is in that position.
            // This is the only thing that changes in the lines of code inside the buttons.
            game.setGrid(grid);
            
        }
        else{
           turn_label1.setText("player2 turn: "+name2);
            a2.setText("O");
            turn=1;
            
            grid=game.getGrid();
            grid[0][0][1]=2;
            game.setGrid(grid);
           
        }
      game.setTurn(turn); // set the last turn change.
      result=game.checkWin(); // checks if someone has won.
      if(result=="PLAYER 1 WON"){
          turn_label1.setText("player 1: "+name1);
      }
      if(result=="PLAYER 2 WON"){
          turn_label1.setText("player 2: "+name2);
      }
      results_label.setText(result); // set the text if someone has won.
       }
    }//GEN-LAST:event_a2MouseClicked

    private void menu_button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_button1MouseClicked
        new Menu().setVisible(true); // reopens the menu frame.
        setVisible(false);
    }//GEN-LAST:event_menu_button1MouseClicked

    private void a3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a3MouseClicked
       if(a3.getText()==""&&result==""){ 
        if(turn==1){
            turn_label1.setText("player1 turn: "+name1);
            a3.setText("X");
            turn=0;
            grid=game.getGrid();
            grid[0][0][2]=1;
            game.setGrid(grid);
            
        }
        else{
            turn_label1.setText("player2 turn: "+name2);
            a3.setText("O");
            turn=1;
            grid=game.getGrid();
            grid[0][0][2]=2;
            game.setGrid(grid);
            
        }
    game.setTurn(turn);
    result=game.checkWin();
    if(result=="PLAYER 1 WON"){
          turn_label1.setText("player 1: "+name1);
      }
      if(result=="PLAYER 2 WON"){
          turn_label1.setText("player 2: "+name2);
      }
      results_label.setText(result);
       }
    }//GEN-LAST:event_a3MouseClicked

    private void a4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a4MouseClicked
        if(a4.getText()==""&&result==""){
        if(turn==1){
            turn_label1.setText("player1 turn: "+name1);
            a4.setText("X");
            turn=0;
            grid=game.getGrid();
            grid[0][1][0]=1;
            game.setGrid(grid);
        }
        else{
            turn_label1.setText("player2 turn: "+name2);
            a4.setText("O");
            turn=1;
            grid=game.getGrid();
            grid[0][1][0]=2;
            game.setGrid(grid);
        }
    game.setTurn(turn);
    result=game.checkWin();
    if(result=="PLAYER 1 WON"){
          turn_label1.setText("player 1: "+name1);
      }
    if(result=="PLAYER 2 WON"){
          turn_label1.setText("player 2: "+name2);
      }
    results_label.setText(result);
        }
    }//GEN-LAST:event_a4MouseClicked

    private void a1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a1MouseClicked
       if(a1.getText()==""&&result==""){ 
        if(turn==1){
            turn_label1.setText("player1 turn: "+name1);
            a1.setText("X");
            turn=0;
            grid=game.getGrid();
            grid[0][0][0]=1;
            game.setGrid(grid);
           
            
        }
        else{
            turn_label1.setText("player2 turn: "+name2);
            a1.setText("O");
            turn=1;
            grid=game.getGrid();
            grid[0][0][0]=2;
            game.setGrid(grid);
            
        }
     game.setTurn(turn);
     result=game.checkWin();
     if(result=="PLAYER 1 WON"){
          turn_label1.setText("player 1: "+name1);
      }
     if(result=="PLAYER 2 WON"){
          turn_label1.setText("player 2: "+name2);
      }
     results_label.setText(result);
       }
    }//GEN-LAST:event_a1MouseClicked

    private void a5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a5MouseClicked
      if(a5.getText()==""&&result==""){
        if(turn==1){
           turn_label1.setText("player1 turn: "+name1);
            a5.setText("X");
            turn=0;
            grid=game.getGrid();
            grid[0][1][1]=1;
            game.setGrid(grid);
        }
        else{
           turn_label1.setText("player2 turn: "+name2);
            a5.setText("O");
            turn=1;
            grid=game.getGrid();
            grid[0][1][1]=2;
            game.setGrid(grid);
        }
    game.setTurn(turn);
    result=game.checkWin();
    if(result=="PLAYER 1 WON"){
          turn_label1.setText("player 1: "+name1);
      }
    if(result=="PLAYER 2 WON"){
          turn_label1.setText("player 2: "+name2);
    }
    results_label.setText(result);
      }
    }//GEN-LAST:event_a5MouseClicked

    private void a6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a6MouseClicked
       if(a6.getText()==""&&result==""){ 
        if(turn==1){
            turn_label1.setText("player1 turn: "+name1);
            a6.setText("X");
            turn=0;
            grid=game.getGrid();
            grid[0][1][2]=1;
            game.setGrid(grid);
        }
        else{
            turn_label1.setText("player2 turn: "+name2);
            a6.setText("O");
            turn=1;
            grid=game.getGrid();
            grid[0][1][2]=2;
            game.setGrid(grid);
        }
    game.setTurn(turn);
    result=game.checkWin();
    if(result=="PLAYER 1 WON"){
          turn_label1.setText("player 1: "+name1);
    }
      if(result=="PLAYER 2 WON"){
          turn_label1.setText("player 2: "+name2);
    }
    results_label.setText(result);
       }
    }//GEN-LAST:event_a6MouseClicked

    private void a7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a7MouseClicked
       if(a7.getText()==""&&result==""){ 
        if(turn==1){
            turn_label1.setText("player1 turn: "+name1);
            a7.setText("X");
            turn=0;
            grid=game.getGrid();
            grid[0][2][0]=1;
            game.setGrid(grid);
        }
        else{
            turn_label1.setText("player2 turn: "+name2);
            a7.setText("O");
            turn=1;
            grid=game.getGrid();
            grid[0][2][0]=2;
            game.setGrid(grid);
        }
    game.setTurn(turn);
    result=game.checkWin();
    if(result=="PLAYER 1 WON"){
          turn_label1.setText("player 1: "+name1);
      }
    if(result=="PLAYER 2 WON"){
          turn_label1.setText("player 2: "+name2);
    }
    results_label.setText(result);
       }
    }//GEN-LAST:event_a7MouseClicked

    private void a8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a8MouseClicked
       if(a8.getText()==""&&result==""){ 
        if(turn==1){
            turn_label1.setText("player1 turn: "+name1);
            a8.setText("X");
            turn=0;
            grid=game.getGrid();
            grid[0][2][1]=1;
            game.setGrid(grid);
        }
        else{
            turn_label1.setText("player2 turn: "+name2);
            a8.setText("O");
            turn=1;
            grid=game.getGrid();
            grid[0][2][1]=2;
            game.setGrid(grid);
        }
    game.setTurn(turn);
    result=game.checkWin();
    if(result=="PLAYER 1 WON"){
          turn_label1.setText("player 1: "+name1);
    }
    if(result=="PLAYER 2 WON"){
          turn_label1.setText("player 2: "+name2);
    }
    results_label.setText(result);
       }
    }//GEN-LAST:event_a8MouseClicked

    private void a9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a9MouseClicked
       if(a9.getText()==""&&result==""){ 
        if(turn==1){
            turn_label1.setText("player1 turn: "+name1);
            a9.setText("X");
            turn=0;
            grid=game.getGrid();
            grid[0][2][2]=1;
            game.setGrid(grid);
        }
        else{
            turn_label1.setText("player2 turn: "+name2);
            a9.setText("O");
            turn=1;
            grid=game.getGrid();
            grid[0][2][2]=2;
            game.setGrid(grid);
        }
    game.setTurn(turn);
    result=game.checkWin();
    if(result=="PLAYER 1 WON"){
          turn_label1.setText("player 1: "+name1);
      }
    if(result=="PLAYER 2 WON"){
          turn_label1.setText("player 2: "+name2);
      }
    results_label.setText(result);
       }
    }//GEN-LAST:event_a9MouseClicked

    private void b1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseClicked
       if(b1.getText()==""&&result==""){
        if(turn==1){
            turn_label1.setText("player1 turn: "+name1);
            b1.setText("X");
            turn=0;
            grid=game.getGrid();
            grid[1][0][0]=1;
            game.setGrid(grid);
        }
        else{
            turn_label1.setText("player2 turn: "+name2);
            b1.setText("O");
            turn=1;
            grid=game.getGrid();
            grid[1][0][0]=2;
            game.setGrid(grid);
        }
    game.setTurn(turn);
    result=game.checkWin();
    if(result=="PLAYER 1 WON"){
          turn_label1.setText("player 1: "+name1);
      }
    if(result=="PLAYER 2 WON"){
          turn_label1.setText("player 2: "+name2);
      }
    results_label.setText(result);
       }
    }//GEN-LAST:event_b1MouseClicked

    private void b2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2MouseClicked
       if(b2.getText()==""&&result==""){ 
        if(turn==1){
            turn_label1.setText("player1 turn: "+name1);
            b2.setText("X");
            turn=0;
            grid=game.getGrid();
            grid[1][0][1]=1;
            game.setGrid(grid);
        }
        else{
            turn_label1.setText("player2 turn: "+name2);
            b2.setText("O");
            turn=1;
            grid=game.getGrid();
            grid[1][0][1]=2;
            game.setGrid(grid);
        }
    game.setTurn(turn);
    result=game.checkWin();
    if(result=="PLAYER 1 WON"){
          turn_label1.setText("player 1: "+name1);
      }
    if(result=="PLAYER 2 WON"){
          turn_label1.setText("player 2: "+name2);
      }
    results_label.setText(result);
       }
    }//GEN-LAST:event_b2MouseClicked

    private void b3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b3MouseClicked
       if(b3.getText()==""&&result==""){
        if(turn==1){
           turn_label1.setText("player1 turn: "+name1);
            b3.setText("X");
            turn=0;
            grid=game.getGrid();
            grid[1][0][2]=1;
            game.setGrid(grid);
        }
        else{
           turn_label1.setText("player2 turn: "+name2);
            b3.setText("O");
            turn=1;
            grid=game.getGrid();
            grid[1][0][2]=2;
            game.setGrid(grid);
        }
    game.setTurn(turn);
    result=game.checkWin();
    if(result=="PLAYER 1 WON"){
          turn_label1.setText("player 1: "+name1);
      }
    if(result=="PLAYER 2 WON"){
          turn_label1.setText("player 2: "+name2);
      }
    results_label.setText(result);
       }
    }//GEN-LAST:event_b3MouseClicked

    private void b4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b4MouseClicked
      if(b4.getText()==""&&result==""){  
        if(turn==1){
            turn_label1.setText("player1 turn: "+name1);
            b4.setText("X");
            turn=0;
            grid=game.getGrid();
            grid[1][1][0]=1;
            game.setGrid(grid);
        }
        else{
            turn_label1.setText("player2 turn: "+name2);
            b4.setText("O");
            turn=1;
            grid=game.getGrid();
            grid[1][1][0]=2;
            game.setGrid(grid);
        }
    game.setTurn(turn);
    result=game.checkWin();
    if(result=="PLAYER 1 WON"){
          turn_label1.setText("player 1: "+name1);
      }
    if(result=="PLAYER 2 WON"){
          turn_label1.setText("player 2: "+name2);
      }
    results_label.setText(result);
      }
    }//GEN-LAST:event_b4MouseClicked

    private void b5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b5MouseClicked
       if(b5.getText()==""&&result==""){ 
        if(turn==1){
            turn_label1.setText("player1 turn: "+name1);
            b5.setText("X");
            turn=0;
            grid=game.getGrid();
            grid[1][1][1]=1;
            game.setGrid(grid);
        }
        else{
            turn_label1.setText("player2 turn: "+name2);
            b5.setText("O");
            turn=1;
            grid=game.getGrid();
            grid[1][1][1]=2;
            game.setGrid(grid);
        }
    game.setTurn(turn);
    result=game.checkWin();
    if(result=="PLAYER 1 WON"){
          turn_label1.setText("player 1: "+name1);
      }
    if(result=="PLAYER 2 WON"){
          turn_label1.setText("player 2: "+name2);
      }
    results_label.setText(result);
       }
    }//GEN-LAST:event_b5MouseClicked

    private void b6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b6MouseClicked
      if(b6.getText()==""&&result==""){  
        if(turn==1){
            turn_label1.setText("player1 turn: "+name1);
            b6.setText("X");
            turn=0;
            grid=game.getGrid();
            grid[1][1][2]=1;
            game.setGrid(grid);
        }
        else{
            turn_label1.setText("player2 turn: "+name2);
            b6.setText("O");
            turn=1;
            grid=game.getGrid();
            grid[1][1][2]=2;
            game.setGrid(grid);
        }
    game.setTurn(turn);
    result=game.checkWin();
    if(result=="PLAYER 1 WON"){
          turn_label1.setText("player 1: "+name1);
      }
    if(result=="PLAYER 2 WON"){
          turn_label1.setText("player 2: "+name2);
      }
    results_label.setText(result);
      }
    }//GEN-LAST:event_b6MouseClicked

    private void b7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b7MouseClicked
       if(b7.getText()==""&&result==""){ 
        if(turn==1){
            turn_label1.setText("player1 turn: "+name1);
            b7.setText("X");
            turn=0;
            grid=game.getGrid();
            grid[1][2][0]=1;
            game.setGrid(grid);
        }
        else{
            turn_label1.setText("player2 turn: "+name2);
            b7.setText("O");
            turn=1;
            grid=game.getGrid();
            grid[1][2][0]=2;
            game.setGrid(grid);
        }
    game.setTurn(turn);
    result=game.checkWin();
    if(result=="PLAYER 1 WON"){
          turn_label1.setText("player 1: "+name1);
      }
    if(result=="PLAYER 2 WON"){
          turn_label1.setText("player 2: "+name2);
      }
    results_label.setText(result);
       }
    }//GEN-LAST:event_b7MouseClicked

    private void b8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b8MouseClicked
       if(b8.getText()==""&&result==""){
        if(turn==1){
            turn_label1.setText("player1 turn: "+name1);
            b8.setText("X");
            turn=0;
            grid=game.getGrid();
            grid[1][2][1]=1;
            game.setGrid(grid);
        }
        else{
            turn_label1.setText("player2 turn: "+name2);
            b8.setText("O");
            turn=1;
            grid=game.getGrid();
            grid[1][2][1]=2;
            game.setGrid(grid);
        }
    game.setTurn(turn);
    result=game.checkWin();
    if(result=="PLAYER 1 WON"){
          turn_label1.setText("player 1: "+name1);
      }
    if(result=="PLAYER 2 WON"){
          turn_label1.setText("player 2: "+name2);
      }
    results_label.setText(result);
       }
    }//GEN-LAST:event_b8MouseClicked

    private void b9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b9MouseClicked
       if(b9.getText()==""&&result==""){ 
        if(turn==1){
            turn_label1.setText("player1 turn: "+name1);
            b9.setText("X");
            turn=0;
            grid=game.getGrid();
            grid[1][2][2]=1;
            game.setGrid(grid);
        }
        else{
            turn_label1.setText("player2 turn: "+name2);
            b9.setText("O");
            turn=1;
            grid=game.getGrid();
            grid[1][2][2]=2;
            game.setGrid(grid);
        }
    game.setTurn(turn);
    result=game.checkWin();
    if(result=="PLAYER 1 WON"){
          turn_label1.setText("player 1: "+name1);
      }
    if(result=="PLAYER 2 WON"){
          turn_label1.setText("player 2: "+name2);
      }
    results_label.setText(result);
       }
    }//GEN-LAST:event_b9MouseClicked

    private void c8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c8MouseClicked
       if(c8.getText()==""&&result==""){
        if(turn==1){
            turn_label1.setText("player1 turn: "+name1);
            c8.setText("X");
            turn=0;
            grid=game.getGrid();
            grid[2][2][1]=1;
            game.setGrid(grid);
        }
        else{
            turn_label1.setText("player2 turn: "+name2);
            c8.setText("O");
            turn=1;
            grid=game.getGrid();
            grid[2][2][1]=2;
            game.setGrid(grid);
        }
    game.setTurn(turn);
    result=game.checkWin();
    if(result=="PLAYER 1 WON"){
          turn_label1.setText("player 1: "+name1);
      }
    if(result=="PLAYER 2 WON"){
          turn_label1.setText("player 2: "+name2);
      }
    results_label.setText(result);
       }
    }//GEN-LAST:event_c8MouseClicked

    private void c5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c5MouseClicked
       if(c5.getText()==""&&result==""){ 
        if(turn==1){
            turn_label1.setText("player1 turn: "+name1);
           c5.setText("X");
            turn=0;
            grid=game.getGrid();
            grid[2][1][1]=1;
            game.setGrid(grid);
        }
        else{
            turn_label1.setText("player2 turn: "+name2);
            c5.setText("O");
            turn=1;
            grid=game.getGrid();
            grid[2][1][1]=2;
            game.setGrid(grid);
        }
    game.setTurn(turn);
    result=game.checkWin();
    if(result=="PLAYER 1 WON"){
          turn_label1.setText("player 1: "+name1);
      }
    if(result=="PLAYER 2 WON"){
          turn_label1.setText("player 2: "+name2);
      }
    results_label.setText(result);
       }
    }//GEN-LAST:event_c5MouseClicked

    private void c1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c1MouseClicked
      if(c1.getText()==""&&result==""){  
        if(turn==1){
            turn_label1.setText("player1 turn: "+name1);
            c1.setText("X");
            turn=0;
            grid=game.getGrid();
            grid[2][0][0]=1;
            game.setGrid(grid);
        }
        else{
            turn_label1.setText("player2 turn: "+name2);
           c1.setText("O");
            turn=1;
            grid=game.getGrid();
            grid[2][0][0]=2;
            game.setGrid(grid);
        }
    game.setTurn(turn);
    result=game.checkWin();
    if(result=="PLAYER 1 WON"){
          turn_label1.setText("player 1: "+name1);
      }
    if(result=="PLAYER 2 WON"){
          turn_label1.setText("player 2: "+name2);
      }
    results_label.setText(result);
      }
    }//GEN-LAST:event_c1MouseClicked

    private void c6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c6MouseClicked
       if(c6.getText()==""&&result==""){ 
        if(turn==1){
            turn_label1.setText("player1 turn: "+name1);
            c6.setText("X");
            turn=0;
            grid=game.getGrid();
            grid[2][1][2]=1;
            game.setGrid(grid);
        }
        else{
            turn_label1.setText("player2 turn: "+name2);
            c6.setText("O");
            turn=1;
            grid=game.getGrid();
            grid[2][1][2]=2;
            game.setGrid(grid);
        }
    game.setTurn(turn);
    result=game.checkWin();
    if(result=="PLAYER 1 WON"){
          turn_label1.setText("player 1: "+name1);
      }
    if(result=="PLAYER 2 WON"){
          turn_label1.setText("player 2: "+name2);
      }
    results_label.setText(result);
       }
    }//GEN-LAST:event_c6MouseClicked

    private void c4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c4MouseClicked
      if(c4.getText()==""&&result==""){  
        if(turn==1){
            turn_label1.setText("player1 turn: "+name1);
            c4.setText("X");
            turn=0;
            grid=game.getGrid();
            grid[2][1][0]=1;
            game.setGrid(grid);
        }
        else{
            turn_label1.setText("player2 turn: "+name2);
            c4.setText("O");
            turn=1;
            grid=game.getGrid();
            grid[2][1][0]=2;
            game.setGrid(grid);
        }
    game.setTurn(turn);
    result=game.checkWin();
    if(result=="PLAYER 1 WON"){
          turn_label1.setText("player 1: "+name1);
      }
    if(result=="PLAYER 2 WON"){
          turn_label1.setText("player 2: "+name2);
      }
    results_label.setText(result);
      }
    }//GEN-LAST:event_c4MouseClicked

    private void c9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c9MouseClicked
      if(c9.getText()==""&&result==""){  
        if(turn==1){
            turn_label1.setText("player1 turn: "+name1);
            c9.setText("X");
            turn=0;
            grid=game.getGrid();
            grid[2][2][2]=1;
            game.setGrid(grid);
        }
        else{
            turn_label1.setText("player2 turn: "+name2);
            c9.setText("O");
            turn=1;
            grid=game.getGrid();
            grid[2][2][2]=2;
            game.setGrid(grid);
        }
    game.setTurn(turn);
    result=game.checkWin();
    if(result=="PLAYER 1 WON"){
          turn_label1.setText("player 1: "+name1);
      }
    if(result=="PLAYER 2 WON"){
          turn_label1.setText("player 2: "+name2);
      }
    results_label.setText(result);
      }
    }//GEN-LAST:event_c9MouseClicked

    private void c2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c2MouseClicked
     if(c2.getText()==""&&result==""){  
        if(turn==1){
            turn_label1.setText("player1 turn: "+name1);
            c2.setText("X");
            turn=0;
            grid=game.getGrid();
            grid[2][0][1]=1;
            game.setGrid(grid);
        }
        else{
            turn_label1.setText("player2 turn: "+name2);
            c2.setText("O");
            turn=1;
            grid=game.getGrid();
            grid[2][0][1]=2;
            game.setGrid(grid);
        }
    game.setTurn(turn);
    result=game.checkWin();
    if(result=="PLAYER 1 WON"){
          turn_label1.setText("player 1: "+name1);
      }
    if(result=="PLAYER 2 WON"){
          turn_label1.setText("player 2: "+name2);
    }
    results_label.setText(result);
     }
    }//GEN-LAST:event_c2MouseClicked

    private void c7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c7MouseClicked
      if(c7.getText()==""&&result==""){ 
        if(turn==1){
            turn_label1.setText("player1 turn: "+name1);
            c7.setText("X");
            turn=0;
            grid=game.getGrid();
            grid[2][2][0]=1;
            game.setGrid(grid);
        }
        else{
            turn_label1.setText("player2 turn: "+name2);
            c7.setText("O");
            turn=1;
            grid=game.getGrid();
            grid[2][2][0]=2;
            game.setGrid(grid);
        }
    game.setTurn(turn);
    result=game.checkWin();
    if(result=="PLAYER 1 WON"){
          turn_label1.setText("player 1: "+name1);
      }
      if(result=="PLAYER 2 WON"){
          turn_label1.setText("player 2: "+name2);
      }
    results_label.setText(result);
      }
    }//GEN-LAST:event_c7MouseClicked

    private void c3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c3MouseClicked
       if(c3.getText()==""&&result==""){ 
        if(turn==1){
            turn_label1.setText("player1 turn: "+name1);
            c3.setText("X");
            turn=0;
            grid=game.getGrid();
            grid[2][0][2]=1;
            game.setGrid(grid);
        }
        else{
            turn_label1.setText("player2 turn: "+name2);
            c3.setText("O");
            turn=1;
            grid=game.getGrid();
            grid[2][0][2]=2;
            game.setGrid(grid);
        }
    game.setTurn(turn);
    result=game.checkWin();
    if(result=="PLAYER 1 WON"){
          turn_label1.setText("player 1: "+name1);
      }
    if(result=="PLAYER 2 WON"){
          turn_label1.setText("player 2: "+name2);
      }
    results_label.setText(result);
       }
    }//GEN-LAST:event_c3MouseClicked

    private void save_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save_buttonMouseClicked

        file_label.setVisible(true); // sets the screen componenets to be displayed or not displayed.
        done_button.setVisible(true);
        filename_field.setVisible(true);
        save_button.setVisible(false);
    }//GEN-LAST:event_save_buttonMouseClicked

    private void done_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_done_buttonMouseClicked
        String filename=""; // saves the game.
        filename="src/logic/"+filename_field.getText();
        game_writer.writer(game, filename);
        file_label.setVisible(false);
        save_label.setVisible(true);
        done_button.setVisible(false);
        filename_field.setVisible(false);
    }//GEN-LAST:event_done_buttonMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton a1;
    private javax.swing.JButton a2;
    private javax.swing.JButton a3;
    private javax.swing.JButton a4;
    private javax.swing.JButton a5;
    private javax.swing.JButton a6;
    private javax.swing.JButton a7;
    private javax.swing.JButton a8;
    private javax.swing.JButton a9;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JLabel background;
    private javax.swing.JButton c1;
    private javax.swing.JButton c2;
    private javax.swing.JButton c3;
    private javax.swing.JButton c4;
    private javax.swing.JButton c5;
    private javax.swing.JButton c6;
    private javax.swing.JButton c7;
    private javax.swing.JButton c8;
    private javax.swing.JButton c9;
    private javax.swing.JButton done_button;
    private javax.swing.JLabel dots_gif;
    private javax.swing.JLabel file_label;
    private javax.swing.JTextField filename_field;
    private javax.swing.JLabel layerA_graphic;
    private javax.swing.JLabel layerB_graphic;
    private javax.swing.JLabel layerC_graphic;
    private javax.swing.JButton menu_button1;
    private javax.swing.JLabel results_label;
    private javax.swing.JButton save_button;
    private javax.swing.JLabel save_label;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel tresd;
    private javax.swing.JLabel turn_label1;
    private javax.swing.JLabel turn_label2;
    private javax.swing.JLabel turn_label3;
    private javax.swing.JLabel turn_label4;
    private javax.swing.JLabel turn_label5;
    private javax.swing.JLabel turn_label6;
    private javax.swing.JLabel turn_label7;
    // End of variables declaration//GEN-END:variables
}
